### ISSUE TITLE
Coudn't enable Cloud Access

### ISSUE THREAD

**Issue by niiv0832** [gozoinks/unifi-pfsense#106]
pf 2.4.3
unifi controller ver. 5.7.23
/usr/sbin/pkg config abi = FreeBSD:11:amd64

"Cloud access is not compatible with this OS architecture."

UBNT Support wright: "You will need to install 64 Bit java on your computer"

**Comment by shaneallgeier** [comment]
Could you run this command on the shell and tell us what the output is?
```bash
/usr/sbin/pkg config abi
```

**Comment by niiv0832** [comment]
FreeBSD:11:amd64

**Comment by miguelUncorked** [comment]
Same problem here. Am a noobie. Should I just install 64bit Java?

**Comment by abjugard** [comment]
I'm also having this issue, and running 64-bit pfSense. Anyone know what is going on? Cloud Access was working fine before I reinstalled pfSense (on the same hardware), and now I can't enable it.

**Comment by fvargasfrank** [comment]
Im having the same issue amd64, do you have any update?

**Comment by gnkidwell** [comment]
Cloud access is not officially supported by Ubiquiti on non supported OS's such as UNIX. Closing this issue for now.
