### ISSUE TITLE
document how to disable unifi.sh service and how to remove it

### ISSUE THREAD

**Issue by ssbarnea** [gozoinks/unifi-pfsense#109]
Two sections are missing from the documentation:
* how to disable service so it would not auto-start
* how to remove the service

I am asking this because I am migrating from running unifi controller on pfsense router to running it as a docker container on Synology, as that variant sorts two important issues: free upgrades (due to container architecture), and reliability on system upgrades. pfsense still has its role as is used as a frontend which redirects all ports used by unify and also provides SSL encryption (haproxy) for the two ports needing it.

**Comment by gnkidwell** [comment]
Uninstall Instructions are listed under the readme.md now...
