### ISSUE TITLE
Check for tmp space before install, make TMPDIR

### ISSUE THREAD

**Issue by leifnel** [gozoinks/unifi-pfsense#110]
The default size of /tmp is 40MB, so the installation fails when installing mongodb, where the size of mongodb-2.6.12_4.txz.XXXXX is 46MB

In case the tmp is too small, the script should either just stop, or offer to make a TMPDIR at for instance /usr/local/tmp or a user-selectable path.

I solved it by

```
sh 
mkdir /usr/local/tmp
TMPDIR=/usr/local/tmp; export TMPDIR

```

**Comment by gnkidwell** [comment]
This has already been resolved in the latest scripts, but not by this exact method. Closing this for now.
