### ISSUE TITLE
Web Configurator timeout/stalling issues after installing 5.8.28

### ISSUE THREAD

**Issue by code31** [gozoinks/unifi-pfsense#118]
Hello!

I installed the latest script using ` fetch -o - https://git.io/j7Jy | sh -s` last night. I really appreciate all of the hard work everyone has done to make this installation a possibility. It removed the need to have separate server hardware running. Unfortunately, I am having some general performance issues with the web configurator after installing. 

The web configurator is very slow or times out under the following scenarios:

- running `service unifi.sh start` from web CLI. I have to let it timeout on the CLI page. Otherwise, if I attempt to navigate away from it, the web interface is unresponsive until it times out in the background. This is very consistent behavior.

- Whether Unifi is started or not, most of the time, the web configurator requires the "Apply Changes" action it times out to the 504/nginx page. In the rare case, it takes a very long time to refresh the page, but the action completes successfully. Here is a good example of that with the Unbound DNS server:

     For the sake of documentation:
    - Make a change to the Unbound configuration via web config
    - Click the blue 'save' button
    - It loads the 'apply changes' banner/button at the top of the page within the normal amount of time.
    - Click 'apply changes' and that is when the web configurator stalls
   
     Now, if you go to the web CLI you can refresh Unbound without stalling (most of the time) by running these:
    - `unbound-control -c /var/unbound/unbound.conf stop`
    - `unbound-control -c /var/unbound/unbound.conf start` 

     Or this:
    - `unbound-control -c /var/unbound/unbound.conf reload`

System details:

- Supermicro board with Dual core Atom D510 @ 1.66 GHz - hyperthreading disabled
- Intel ethernet
- 4 GB non-ecc ram
- PFSense 2.4.3-RELEASE-p1 using ZFS
- Unifi Controller 5.8.28

System loads with Unifi controller enabled:

- Memory usage never goes above 51% 
- CPU usage usually between 3-15%

Output of `top -dl` with Unifi enabled:

![image](https://user-images.githubusercontent.com/42047788/45267158-ef3b4600-b42c-11e8-97d2-4e5137304647.png)

And with Unifi disabled:

![image](https://user-images.githubusercontent.com/42047788/45267216-e5fea900-b42d-11e8-9496-25ccb3fda17a.png)

Some curiosities:

- Should java be using 462M of memory and 849 threads? 
- Are all of the rc scripts reloaded when clicking 'apply changes' to sync the system state? If so, could the unifi rc script be causing problems?

Logs:

- [mongod.log](https://github.com/gozoinks/unifi-pfsense/files/2364530/mongod.log)
- [nginx_errors.log](https://github.com/gozoinks/unifi-pfsense/files/2364536/nginx_errors.log)

For now, I stop the Unifi controller when I am not configuring the AP to keep Java and Mongodb from consuming too many resources.  However, ideally, I would like it to run without causing issues with the web configurator. (I understand this may be an issue with the dependencies/Unifi controller software and not this project)

I am stumped on how to fix this because other than general slowness and the timeout message, I have no logs to go on (at least that I can find). Has anyone experienced this or have a starting point for remediating the issue?

Thank you for your time!

**Comment by EliasGabrielsson** [comment]
I have similar problem. It's look like it related to mongodb

```
top: warning: display count should be positive -- option ignored
....
last pid: 97932;  load averages:  0.32,  0.29,  0.19  up 0+00:16:53    11:57:23
44 processes:  1 running, 42 sleeping, 1 stopped

Mem: 1299M Active, 141M Inact, 648K Laundry, 363M Wired, 188M Buf, 23M Free
Swap: 4096M Total, 4096M Free


  PID USERNAME  THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
28781 root       21  20    0  2403M   969M STOP    0   0:22  11.96% mongod
97932 root        1  20    0 20068K  2880K CPU1    1   0:00   0.59% top
  323 root        1  21    0   261M 31600K piperd  3   0:06   0.49% php-fpm
89289 root      844  52    0  2159M   402M uwait   1   1:56   0.00% java
  324 root        1  52    0   265M 30876K accept  3   0:05   0.00% php-fpm
40351 unbound     4  20    0 72964K 25012K kqread  2   0:02   0.00% unbound
32838 root        5  52    0 10988K  2320K uwait   3   0:01   0.00% dpinger
56064 root        1  52   20 13096K  2524K wait    2   0:00   0.00% sh
44895 root        1  20    0 37752K  7664K kqread  0   0:00   0.00% nginx
30877 root        1  20    0 12736K  2180K bpf     2   0:00   0.00% filterlog
45616 root        1  20    0 24656K 12480K select  3   0:00   0.00% ntpd
50176 dhcpd       1  20    0 16656K  6652K select  2   0:00   0.00% dhcpd
85508 root        1  20    0 10488K  2520K select  0   0:00   0.00% syslogd
44927 root        1  20    0 37752K  7680K kqread  0   0:00   0.00% nginx
  322 root        1  20    0   259M 20288K kqread  1   0:00   0.00% php-fpm
23280 root        1  52    0 39440K  2772K wait    0   0:00   0.00% login
24547 root        1  52    0 39440K  2772K wait    2   0:00   0.00% login
  361 root        1  40   20 19456K  4268K kqread  0   0:00   0.00% check_reload_status
```

**Comment by jmbwell** [comment]
What system architecture?

**Comment by code31** [comment]
@jmbwell AMD64

**Comment by marcosboosa** [comment]
![image](https://user-images.githubusercontent.com/16392414/47086306-7d0a0e00-d1ef-11e8-9ea5-b8cbbb645c73.png)

not starting ....

**Comment by jsteigerwalt-ss** [comment]
I have experienced the same issue trying to get the Unifi Controller to run on OPNsense 18.7 (amd64/OpenSSL)

**Comment by iwex** [comment]
The same issue here. Any updates, where can I find some logs?

**Comment by gnkidwell** [comment]
Stale issue closing for now.
