### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by mgillette73** [gozoinks/unifi-pfsense#123]
Followed the install to a T. everything went great, now I am getting this error when trying to log into the controller via port 8443

"Bad Request
This combination of host and port requires TLS."

Any ideas of what or how I can fix this. Or if this is even the correct place to ask for support.

Thanks

**Comment by drummerclint** [comment]
Sounds like you're using http.  Use https:// before your hostname/ip

**Comment by gnkidwell** [comment]
Closing this issue for now, user was not using https
