### ISSUE TITLE
Unifi-Video

### ISSUE THREAD

**Issue by bipple294** [gozoinks/unifi-pfsense#124]
Would this be able to be changed to install the Unifi Video software also?

I was looking into installing the NVR software into a FreeNAS jail and was wondering.

**Comment by gnkidwell** [comment]
> Would this be able to be changed to install the Unifi Video software also?
> 
> I was looking into installing the NVR software into a FreeNAS jail and was wondering.

Considering, that the Unifi Video project is officially no longer supported by Ubiquiti, this will not be able to be supported. Closing this for now.
