### ISSUE TITLE
Failure after upgrading to pfsense 4/13/15

### ISSUE THREAD

**Issue by wijagels** [gozoinks/unifi-pfsense#13]
After running the updater, the unifi controller refused to start.  I found that mongodb was failing due to libpcrecpp.so.0 missing.  Running 

```
pkg install -f pcre
```

fixed the issue of mongodb.  Hopefully this helps someone who runs into this problem.

**Comment by gozoinks** [comment]
Thanks for reporting this! If libpcre is missing in the latest version,
we'll have to include that, but I'm surprised mongodb's package didn't
bring it along as a dependency. Any idea what's happening here?

On Mon, Apr 27, 2015 at 10:16 PM, William Jagels <notifications@github.com>
wrote:

> After running the updater, the unifi controller refused to start. I found
> that mongodb was failing due to libpcrecpp.so.0 missing. Running
>
> pkg install -f pcre
>
> fixed the issue of mongodb. Hopefully this helps someone who runs into
> this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gozoinks/unifi-pfsense/issues/13>.
>



-- 

j

**Comment by wijagels** [comment]
When I ran 

    pkg install pcre

The system **did** report it as installed.  So I guess that the package is there, but for some reason the libpcrecpp.so.0 file wasn't where mongo was looking.  [This thread](https://forums.freebsd.org/threads/libpcre-so-0-problem.29858/) had a similar problem, but I'm not sure what about the pfsense updater might have caused this.

**Comment by marcodc** [comment]
Hi, i had the same issue managed to fix it with removing pcre (will also remove mongodb) then just install via pkg install pcre mongodb (did not loose any settings or anything all was working like a charm after.

**Comment by dannyeuu** [comment]
@gozoinks @marcodc  I have a problem after upgrading from pfSense 2.2.4 to 2.2.6, the UniFi controller not start and I cannot see any log :(

**Comment by dannyeuu** [comment]
was the same error `pkg install -f pcre` works too :+1:

**Comment by marcodc** [comment]
Great! yeah if you update pfSense it will almost always break Unifi controller. happy the fix worked for you

**Comment by jmcphail** [comment]
Worked for me as well. Thanks!

**Comment by gnkidwell** [comment]
Stale issue closing for now
