### ISSUE TITLE
Please Wait..UniFi Controller Starting Up

### ISSUE THREAD

**Issue by kklouzal** [gozoinks/unifi-pfsense#131]
So I ran the install script today to update to the latest controller and now I can't access it
![image](https://user-images.githubusercontent.com/2928845/50043241-f0809e00-002d-11e9-89dc-377d93da9a8f.png)
Not sure where to start diagnosing this, can anyone help me?
These are the current system packages
![image](https://user-images.githubusercontent.com/2928845/50043312-f62ab380-002e-11e9-94a7-9579a0b0a10b.png)
And what System Activity looks like
![image](https://user-images.githubusercontent.com/2928845/50043328-3d18a900-002f-11e9-9b86-30d1c1037b73.png)
![image](https://user-images.githubusercontent.com/2928845/50043346-aef0f280-002f-11e9-8b8f-1115a2ebbaea.png)

**Comment by kklouzal** [comment]
After some digging around online and in the shell i discovered that `/usr/local/UniFi/data/db` was corrupt preventing mongod from starting up. Deleting this directory allowed the controller to fully startup.

I was able to grab an old but relatively new backup of the unifi controller data from `/usr/local/UniFi/data-20181002-0553/backup` and setup the controller with that. Not much configuration was lost thankfully.

**Comment by Darkoth** [comment]
THANK YOU! coudn't find a solution to this problem anywhere.

**Comment by rdantas-info** [comment]
Precisei instalar o Unifi Controller em um Ubuntu Server e aconteceu a mesma coisa.

**Comment by mauricioasj** [comment]
Também passei pelo mesmo problema. O ubiquiti apresentou problemas, ficou gerando log e encheu a partição do firewall.

Após isso separei as partições do pfsense e instalei o controller em outro servidor linux.

![image](https://user-images.githubusercontent.com/51795947/59452707-b88fc300-8de4-11e9-855a-0eb8cc08d7be.png)
