### ISSUE TITLE
Convert into a pfSense package

### ISSUE THREAD

**Issue by Kage** [gozoinks/unifi-pfsense#147]
Hello,

I really like this installer, but I would love to see it as a real pfSense package.  It would be very useful for myself (and I suspect others) to be able to manage Unifi via the pfSense web UI and leverage the provided functionality from the UI and package manager.  I would be happy to contribute to making this happen, but I'd first like to ask if the maintainers and users of this project would be interested in this goal as well?

Cheers!

**Comment by jmbwell** [comment]
Something like such a package exists:

https://www.freshports.org/net-mgmt/unifi5/

It likely meets many needs.
