### ISSUE TITLE
Error with mongod

### ISSUE THREAD

**Issue by cristianmenghi** [gozoinks/unifi-pfsense#15]
Hi, im upgrade pfsense from a previous version to 2.2 and do a clean install, when i tried to install Unifi but im get this error
[2.2.2-RELEASE][root@fw.localdomain]/usr/local/bin: ./mongod
Illegal instruction (core dumped)

Any idea ?

Thks.

**Comment by gozoinks** [comment]
A core dump means a crash. What kind of system are you on? What's the CPU
and architecture?

On Tue, Jun 9, 2015 at 9:42 AM, Cristian Menghi <notifications@github.com>
wrote:

> Hi, im upgrade pfsense from a previous version to 2.2 and do a clean
> install, when i tried to install Unifi but im get this error
> [2.2.2-RELEASE][root@fw.localdomain]/usr/local/bin: ./mongod
> Illegal instruction (core dumped)
>
> Any idea ?
>
> Thks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gozoinks/unifi-pfsense/issues/15>.
>



-- 

j

**Comment by cristianmenghi** [comment]
Hi, thanks for the reply
Me system is: pfSense 2.2.2-RELEASE-pfSense (i386) on 
hw.machine: i386
hw.model: Intel(R) Celeron(TM) CPU                1300MHz
hw.ncpu: 1
hw.machine_arch: i386

**Comment by gnkidwell** [comment]
Mongodb repair script has been added to the latest version of the PFSense install script. Stale closing this for now.
