### ISSUE TITLE
UniFi Controller is starting up... Please wait a moment

### ISSUE THREAD

**Issue by sinanca** [gozoinks/unifi-pfsense#158]
Hello,
   After installing two weeks after installation did unifi manager no longer opened. unifi manager services I started again, but did not setup again did not happen again. Can you help with the topic?

------------------------------------------------
UniFi Controller is starting up...

Please wait a moment
------------------------------------------------

good work.

**Comment by sinanca** [comment]
a little deeper I've poked and learned the problem of the 8080 port mongodb looked at the logs, but there was no error I deleted the UniFi folder again and re-installed now I've sent back from backup is working :)


step 1 service unifi.sh stop 
step 2 rm -rv /usr/local/UniFi    delete all directory  :) 
step 3 install-unifi.sh  start  and restore backup :)

**Comment by jmbwell** [comment]
Thank you!
