### ISSUE TITLE
java not found on OPNSense

### ISSUE THREAD

**Issue by miodzicho** [gozoinks/unifi-pfsense#159]
Hello, I'm trying to get this working on OPNSense, but stuck with: 
`Starting the unifi service...Starting UniFi controller.
eval: /usr/local/bin/java: not found
 done.`

**Comment by JayGreentree** [comment]
This is because opnsense is a modified version of pfsense and not an exact copy. Not everything that works on pfsense will work on opnsense.

**Comment by Ornias1993** [comment]
@JayGreentree Thank you captain obvious.

@miodzicho 
That being said, it should add Java itself...
According to the OPNSense forum that is...

Did you try installing the Java yourself just to make sure it's installed? and check the install dir...

**Comment by jmbwell** [comment]
Thank you. Things seem to be working on OPNsense now. If not, please open a new issue.

**Comment by Keno** [comment]
I had the same problem. The issue is that the base FreeBSD packages are not enabled by default on OPNSense. This can be changed with the following flag:
```
# cat /usr/local/etc/pkg/repos/FreeBSD.conf
FreeBSD: { enabled: no }
```
Some places on the internet say that it can break OPNSense though, so proceed with caution I suppose.
