### ISSUE TITLE
Website wont load, but the controller is online. 

### ISSUE THREAD

**Issue by Esteidinger** [gozoinks/unifi-pfsense#164]
I am having trouble with the controller website. I can no longer load https://192.168.1.1:8443/manage. 

I know the service is running because my guest wifi is running and as I understand that doesn't work unless you have the controller online. 

I've tried a few different restarts. Any suggestions?

**Comment by bafonso** [comment]
Are you getting a black page? That's what I get, I just installed it for the first time.

**Comment by Esteidinger** [comment]
> Are you getting a black page? That's what I get, I just installed it for the first time.

@bafonso  no, the website doesn't load at all

**Comment by bafonso** [comment]
I found out my issue was that pfblockerNG already uses some of the same ports. This should be checked for in the script and mentioned in the installation notes.

**Comment by Esteidinger** [comment]
I ended up re-installing. I did lose some settings, but that is on me.
