### ISSUE TITLE
vlan setup

### ISSUE THREAD

**Issue by kuludown** [gozoinks/unifi-pfsense#167]
Anyone successful with a unifi vlan setup? Everything works fine except an ssid that I want to be on a separate vlan. Devices try to connect but get no ip address. The vlan is in place in the pfsense config, rules are set up and dhcp is enabled...
Running latest pfsense and unifi controller package.

**Comment by jmcphail** [comment]
What kind of network switch are you using?

**Comment by dvdp** [comment]
We're doing that on our school network - works like a charm.
Tagged VLAN for guest access - make sure you switch ports have the right VLAN settings, then I used a separate NIC on the pfsense box which gets all the tagged traffic so you need to setup that interface in pfSense too. Next make the NAT en firewall rules to allow internet traffic from/to that tagged network and you're done.  
For the local traffic, squjid is in between - for the guest traffic, all goes straight to the internet, no proxy.

**Comment by kuludown** [comment]
I forgot to update this yesterday. I figured out the issue... I hadn't verified the vlan config in pfsense and they were bound to the wan interface. After moving them to lan, it works just as expected.
