### ISSUE TITLE
Latest Unifi Beta is Working

### ISSUE THREAD

**Issue by tlsnine** [gozoinks/unifi-pfsense#170]
Sorry for opening a new "issue"
I just wanted to report that I've been successful installing Unifi Beta 5.13.10.0-g7664a3c6 on OPNsense 20.1.3.
The link I used was: `https://dl.ubnt-ut.com/teunis/wpa3/5.13.10/UniFi.unix.zip`
Thanks for your hard work!!

**Comment by tong2x** [comment]
would unifi 5.12.66 also work?
could you post instruction in opnsense forum topic 5469.3
