### ISSUE TITLE
Python 2 package cannot be installed on pfSense 2.4.5

### ISSUE THREAD

**Issue by envescent** [gozoinks/unifi-pfsense#175]
Having trouble with the installation. I was able to rectify the MongoDB 3.4 issue by instead installing 3.6, but Python is unable to install. Attempting to do so asks if we want to remove the core pfSense packages and a PHP 7.2 intl package.

As a result, at least best as I can tell, the web UI is not functional.

**Comment by Tytanium48** [comment]
I have the same issue.

**Comment by HappyShr00m** [comment]
Ya same problem here on 2.4.5 
Starting UniFi controller.
[2.4.5-RELEASE] Port 8080 not available

anyone got a way around this ? Thanks

**Comment by Tytanium48** [comment]
These are the steps I compiled after going through multiple sources and posts.

1) https://community.ui.com/questions/pfSense-with-UniFi-Setup/a6aa5b70-1261-4cb6-9153-0457f7c022a4

2) run the install script
  fetch -o - https://git.io/j7Jy | sh -s

3) manually install the 3 pkgs below
/usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/icu-62.1_2,1.txz
/usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/boost-libs-1.68.0_1.txz
/usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/mongodb34-3.4.16.txz

After I rebooted the pfsense box it was working.

**Comment by HappyShr00m** [comment]
> These are the steps I compiled after going through multiple sources and posts.
> 
> 1. https://community.ui.com/questions/pfSense-with-UniFi-Setup/a6aa5b70-1261-4cb6-9153-0457f7c022a4
>    To work I have to enable FreeBSD repository on /usr/local/share/pfSense/pkg/repos/pfSense-repo.conf
> 
> First line change from
> FreeBSD: { enabled: no }
> to
> FreeBSD: { enabled: yes }
> 
> 1. run the install script
>    fetch -o - https://git.io/j7Jy | sh -s
> 2. manually install the 3 pkgs below
>    /usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/icu-62.1_2,1.txz
>    /usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/boost-libs-1.68.0_1.txz
>    /usr/sbin/pkg add -f https://repo.nepustil.net/111/FreeBSD:11:amd64/.real_1549036267/All/mongodb34-3.4.16.txz
> 
> After I rebooted the pfsense box it was working.

Can't thank you enough. it is working now. hopefully this will be updated in the original script. Thanks again.

**Comment by susobaco** [comment]
Same problem, if I do a new installation following these steps it works, when I reboot the system I get the error:
"Port 8080 not available"

**Comment by dvdp** [comment]
Check if mongo is installed  - if not install it manually (3.6)

**Comment by susobaco** [comment]
Thank you very much, so it seems to be working, I have already restarted the system several times and everything is fine.
I changed the line in the script:

_#AddPkg mongodb34
AddPkg mongodb36_

**Comment by jmbwell** [comment]
Thank you. The script has been updated to address this.
