### ISSUE TITLE
Yes, this can be installed from a package

### ISSUE THREAD

**Issue by dlangille** [gozoinks/unifi-pfsense#178]
In the `README.md` I see:

`Because the UniFi Controller software is proprietary, it cannot be built from source and cannot be included directly in a package. `

This is false.
I install from package. https://www.freshports.org/net-mgmt/unifi5/

It has been available as a FreeBSD package since 2014: https://www.freshports.org/net-mgmt/unifi2/

**Comment by jmbwell** [comment]
Not seeing what’s false. UniFi is still proprietary. Still can’t be built from source. Still can’t be included directly in a pfsense package. 

But you’re perfectly welcome to use freshports.

And anyone with the skills and interest in building a pfsense package for unifi controller is welcome — nay, implored — to do so.
