### ISSUE TITLE
Remote (Cloud) Access

### ISSUE THREAD

**Issue by theonetrueace** [gozoinks/unifi-pfsense#183]
Have several of these boxes in the wild and all of them give me a "Connection failed" when attempting to manage them from the cloud. This isn't a new problem. Wondering if there's something I'm missing about the setup. I'm not blocking outgoing traffic and there should be no need for port forwards for the WebRTC connection.

**Comment by jmbwell** [comment]
Does the problem persist if, say, you spin this up in a test VM?

What if you were to install it by hand?

It's hard to imagine what about this script could cause that, but anything is possible…

**Comment by theonetrueace** [comment]
I haven't tested via VM, but it does still persist on all our boxes currently in the wild. As for a manual install I haven't tested that either. I've just assumed thus far that something in pfsense was blocking the traffic. Can anyone verify they have this working?

**Comment by gnkidwell** [comment]
> I haven't tested via VM, but it does still persist on all our boxes currently in the wild. As for a manual install I haven't tested that either. I've just assumed thus far that something in pfsense was blocking the traffic. Can anyone verify they have this working?

I am currently testing the webrtc issue myself, I too have noticed the same exact problem. I would like to believe it is PFSense, but I will try to confirm the cause...

**Comment by gnkidwell** [comment]
![image](https://user-images.githubusercontent.com/71857593/94290439-cc9afd80-ff1f-11ea-9e97-38b6f95a03bd.png)

Upon further inspection certain ports do need to be open... But what I find interesting is, PFSense does not even detect the connections incoming in the firewall logs...

**Comment by gnkidwell** [comment]
Okay so it appears since the controller is in no way controlling the Unifi Controller Traffic, I say this because port 8443 is wide open on the wan side with no rules indicating it should be. What I would do for now is change the launch mode on unifi to the wan ip address of the boxes in the wild. It will work, but this is a serious security hole, I assume this is why, we should isolate these controllers behind a firewall... My guess is port 443 on the wan side is blocked automatically, and since PFSense does not have controller over Unifi... Well... You can probably see the problem here...

**Comment by gnkidwell** [comment]
Okay, so something that I have found to be common among all installs outside of Unifi hardware is cloud functionality does not appear to work. I tried this on a Ubuntu Server, and a Windows 10 Machine with appropriate firewall rules, and WebRTC constantly gives Connection failed. This appears to be a problem post version 5.9 of the Unifi controller. If you are managing multiple sites, I strongly suggest setting up a VPN server for each site. At the end of the day that is much more secure than WebRTC.

**Comment by ahmedakkaya** [comment]
Can anyone find a solution for remote connection?

**Comment by gnkidwell** [comment]
> Can anyone find a solution for remote connection?

Not yet, this even appears to be an issue on Linux as well...

**Comment by ahmedakkaya** [comment]
Everything is very good and finally I succeeded. It is very nice to have worked unifi for pfsense.
But it's so sad that some things don't work for the remote connection ..

**Comment by gnkidwell** [comment]
> Everything is very good and finally I succeeded. It is very nice to have worked unifi for pfsense.
> But it's so sad that some things don't work for the remote connection ..

Sure but this issue also extends to other self hosted OS... If you run their hardware, cloud connection is not an issue. This is not an issue with PFSense (FreeBSD) or Linux, this is a Ubiquiti issue...

**Comment by ahmedakkaya** [comment]
I created myself a vm test environment
I installed unifi in ubuntu server institution, I tested it
The remote connection is working perfectly

**Comment by gnkidwell** [comment]
> I created myself a vm test environment
> I installed unifi in ubuntu server institution, I tested it
> The remote connection is working perfectly

I just checked too looks like Ubuntu is working again officially. I just found some documentation that remote cloud access is not supported on unofficial Operating Systems. With that being said, UNIX is not an officially supported OS by Ubiquiti. So this feature may never work on UNIX.

**Comment by ahmedakkaya** [comment]
ios mobile app unifi remote connection working
It is very surprising that it does not work in the windows anda mac os  web browser chrome/firefox

**Comment by gnkidwell** [comment]
> ios mobile app unifi remote connection is working
> It is very surprising that it does not work in the windows anda mac os  web browser chrome/firefox

Make sure your phone is not on your wifi or VPN and try again. None of my IOS devices or Android devices will connect externally on remote cloud via the app....

**Comment by ahmedakkaya** [comment]
i am not on the same network and no vpn connection either. 
I access with the ios unifi application

**Comment by gnkidwell** [comment]
> i am not on the same network and no vpn connection either. 
> I access with the ios unifi application

Honestly not sure how it is working on your IOS device and not mine. However, I will tell you I spent several hours months ago trying to get this specific feature to work... Due to documentation that I found today, this is an unsupported feature by Ubiquiti due to it being an unsupported OS. You are more than welcome to, try to figure out what is causing the issue and submit a pull request with the fix. However, by default, a remote cloud feature is nowhere near as secure as a vpn to the site anyway. I would strongly suggest running a vpn for security reasons. All my sites, I have VPN access too...

**Comment by jmbwell** [comment]
It sounds like this is more likely to be an issue with Ubiquiti cloud than with this project. If there's nothing further to be done here, let's close the issue.

**Comment by gnkidwell** [comment]
> It sounds like this is more likely to be an issue with Ubiquiti cloud than with this project. If there's nothing further to be done here, let's close the issue.

I agree, @jmbwell can you close this? I spent too long trying to fix this issue.

**Comment by ahmedakkaya** [comment]
Thank you
i hope this issue works with a patch or an update
I will be following here

**Comment by jmbwell** [comment]
Closing for now. Thanks for all the effort to run this down.
