### ISSUE TITLE
Not an issue, just thank you, works on OPNsense

### ISSUE THREAD

**Issue by peterwi** [gozoinks/unifi-pfsense#184]
Hi,
Just wanted to say massive thanks to all people involved in this project.
It works on latest OPNsense without any problems.

**Comment by tong2x** [comment]
hello

could you post tutorial on how to install?
are you referring to opnsense 20.7?

I seem to be having issues with the current default tutorial

**Comment by tong2x** [comment]
now to update, manage to install using the curent script but it installed the older 5.13.29 firmware

**Comment by peterwi** [comment]
Yes, OPNsense 20.7, I just followed the instructions worked well for me. First tested it on a VM to check.

**Comment by tong2x** [comment]
hope the update to .32?
will be commited soon

**Comment by heyudude** [comment]
5.13.32 works also on 20.7, tested and thanks for creating this indeed

**Comment by jmbwell** [comment]
My thanks to our contributors as well! I'm glad this is useful.
