### ISSUE TITLE
Gateway 504 Error

### ISSUE THREAD

**Issue by jf5264835** [gozoinks/unifi-pfsense#191]
I am unable to run the install script, page just loads for a few minutes and then presents a 504 gateway error, and going to any of the pfSense pages works fine. Install process never appears in the process list on the pfSense box either.

**Comment by gnkidwell** [comment]
Did you ssh in as root on pfsense, and then select shell? After you do that try this Try this instead... 

I am waiting for my additions to be merged. This will put you on 6.0.23 as well...

fetch -o - https://raw.githubusercontent.com/gozoinks/unifi-pfsense/fb58446615f59e582c6eefa406e75e9c984abd3f/install-unifi/install-unifi.sh | sh -s

**Comment by gnkidwell** [comment]
Hey @jf5264835 I went ahead and updated the link to install 6.0.24, please give it a try and leave a review under #201

fetch -o - https://git.io/JUSab | sh -s

**Comment by gnkidwell** [comment]
Closing this issue for now, seems there has been no reply from @jf5264835
