### ISSUE TITLE
What version is downloads, I heard 6 is a terrible mess

### ISSUE THREAD

**Issue by cypherstream** [gozoinks/unifi-pfsense#197]
I'm on 5.12.66.  I'm having an issue where none of my wireless clients show up in the controller.  This is ever since a power outage two days ago.  I updated the firmware on my UniFi equipment and after power cycling my poe switch, when things came back up it showed ALL clients as wired.  Then a few minutes later all the wireless ones that were showing as wired disappeared.  On the topology map it doesn't show anything connected to my UAP Lite, but wireless is working fine.  I restarted the UniFi.sh service and it made no difference.

I'd contemplate running the script again to reinstall the latest version, but I hear UniFi 6 is full of bugs.  Even Lawrence Systems on YouTube warned people not to upgrade yet.  The ubiquiti forums have a lot of complaints about the release.

Does the script install the 6.x train or are you pulling a newer version of the 5.x train?  I'd like to install the last version of 5 before they messed everything up in 6.

**Comment by tong2x** [comment]
have you already restored a backup?

last version is still 5, if you want to reinstall

**Comment by cypherstream** [comment]
Thanks, restoring backup done 8/31 resolved the issue.  I did the restore in the UI and I just had to log into pfsense shell and run service UniFi.sh start and then I'm back in business.

Showing 19 wireless clients.

I heard on Reddit that 6.0.23 fixed the vlan issue that bit everyone in the rear in version 6.

I'd migrate to version 6 someday but I'm ok with letting it bake out there for some time first.

**Comment by tong2x** [comment]
glad to hear

if you ever want to try, there is a pull with the link to the 6.0.23 build

**Comment by cypherstream** [comment]
> glad to hear
> 
> 
> 
> if you ever want to try, there is a pull with the link to the 6.0.23 build

Thanks I'll contemplate it.

Now in the mobile app it shows connection info again.  Also my WiFi throughput is about 200mbps faster than it was.  

My grafana graphs for wireless are now populating again.  I changed it to view the last 7 days and I see that it was the power failure on Friday due to the electric company "rejuvenating underground lines" scheduled outage they had from 12:15 pm to 6:15 pm.  When the ups ran out and I ran a cord to my generator, that's when this weirdness happened.

Glad to have those scheduled backups configured in UniFi.

**Comment by gnkidwell** [comment]
Hey guys, I spent a lot more time on my pull for the updated shell script file... If you are wanting to get 6.0.23, this will do it without any issues 👍🏻 

fetch -o - https://git.io/JUy6Z | sh -s

**Comment by cypherstream** [comment]
Thanks, nice work.  I went from 5.12.66 to 5.14.23 for now.  There's been a lot of complaints on reddit /r/ubiquiti and the ubitiqity forums for version 6, so I'm going to wait a little more yet.  I think 6.0.24 was just released a day or two ago as well.  Ubnt is rushing with small fixes because they screwed this one up so badly (or so it seems from reading the forums).

There was some difficulty going from 5.12.66 to 5.14.23.  I had to play with pkg lock a bit... it completely removed mongodb for one, and I had to research how to add mongodb36 manually, then lock it, then run the script.  Then start the unifi.sh service, restore the backup (which crashes java with a fatal exception), stop the unifi.sh service, start the unifi.sh service, and then I was back in business.

I did find I could remove the package-lock for icu and a newer version loaded on this time (I think it was 61 to icu-67.1,1).  I know in the past installing just about anything in pfsense would remove this and break unifi.  I didn't re-lock the new icu67 package yet but I will consider it.

**Comment by gnkidwell** [comment]
> Thanks, nice work. I went from 5.12.66 to 5.14.23 for now. There's been a lot of complaints on reddit /r/ubiquiti and the ubitiqiti forums for version 6, so I'm going to wait a little more yet. I think 6.0.24 was just released a day or two ago as well. Ubnt is rushing with small fixes because they screwed this one up so badly (or so it seems from reading the forums).
> 
> There was some difficulty going from 5.12.66 to 5.14.23. I had to play with pkg lock a bit... it completely removed mongodb for one, and I had to research how to add mongodb36 manually, then lock it, then run the script. Then start the unifi.sh service, restore the backup (which crashes java with a fatal exception), stop the unifi.sh service, start the unifi.sh service, and then I was back in business.
> 
> I did find I could remove the package-lock for icu and a newer version loaded on this time (I think it was 61 to icu-67.1,1). I know in the past installing just about anything in pfsense would remove this and break unifi. I didn't re-lock the new icu67 package yet but I will consider it.
> 
> The reason I bring up some of that install difficulty is perhaps your script (which looks nicely done btw!) may be doing things in the right order to not cause pkg to remove things incorrectly. I'll want to remove my pkg locks and try it in the future. I'd rather not rely on using pkg lock because then a year down the road you do an upgrade and you forget you had some packages locked and it ends up causing issues.

The updates I made to the original script officially seem to just work. PkgAdd order was changed so dependencies are installed before their dependent Packages... Also, here is a link for 6.0.24 if you want to give it a go...

fetch -o - https://git.io/JUSab | sh -s

**Comment by gnkidwell** [comment]
For now, this script is currently running 6.0.43... However if you would like to run 5.14.23, I still have it linked on my repository. https://github.com/gnkidwell/unifi-pfsense
Closing this for now.
