### ISSUE TITLE
Dependencies not installing before their Packages

### ISSUE THREAD

**Issue by gnkidwell** [gozoinks/unifi-pfsense#205]
@jmbwell @gozoinks ... I have made a couple pull requests for 6.0.23 and 6.0.24, however I have not seen any activity. In those pull requests I also made comments that I had fixed the PkgAdd order to fix dependencies not installing before their packages? I do understand the need to test the controller, however, would you like me to make a separate pull request for fixing the PkgAdd order? Before I fixed this, I could not get the controller running at all on a fresh install of PFSense 2.4.5 FreeBSD 11.3 Stable. A fresh install gives no errors at all aside from a warn message because system.properties cannot be found, even though that is not even the case. The file does exist, that message only exists on the first start of unifi.sh... All subsequent stops and starts do not cause that message to occur. Can we maybe add an additional folder after this merge is completed for Release Candidates and Beta Software as well? This will at least give people more options than just the standard install-unifi.sh?

**Comment by jmbwell** [comment]
I’ve seen the notifications, and I’m excited to take a closer look. I’ll go through it all soon. Thank you for your patience.

**Comment by gnkidwell** [comment]
> I’ve seen the notifications, and I’m excited to take a closer look. I’ll go through it all soon. Thank you for your patience.

Excellent, thanks for your reply :)

**Comment by LuxArcana** [comment]
on a freshly installed pfSence instance, I needed to run pkg install fontconfig before executing the script

it seems that the fontconfig is required for dejavu and dejavu is required for openjdk8

without that the dejavu install would fail and then cascade all the way up

**Comment by gnkidwell** [comment]
> on a freshly installed pfSence instance, I needed to run pkg install fontconfig before executing the script
> 
> it seems that the fontconfig is required for dejavu and dejavu is required for openjdk8
> 
> without that the dejavu install would fail and then cascade all the way up

Have you tried running one of my pull requests? My pull requests do not suffer from this issue.

**Comment by LuxArcana** [comment]
> > on a freshly installed pfSence instance, I needed to run pkg install fontconfig before executing the script
> > it seems that the fontconfig is required for dejavu and dejavu is required for openjdk8
> > without that the dejavu install would fail and then cascade all the way up
> 
> Have you tried running one of my pull requests? My pull requests do not suffer from this issue.

Using the latest Pull Request made it through the install process correctly.  Thanks

**Comment by gnkidwell** [comment]
> > > on a freshly installed pfSence instance, I needed to run pkg install fontconfig before executing the script
> > > it seems that the fontconfig is required for dejavu and dejavu is required for openjdk8
> > > without that the dejavu install would fail and then cascade all the way up
> > 
> > 
> > Have you tried running one of my pull requests? My pull requests do not suffer from this issue.
> 
> Using the latest Pull Request made it through the install process correctly. Thanks

Take a look at #211 they just released the official release of 6.0.28.

**Comment by gnkidwell** [comment]
Have not seen any commit updates, closing this issue (due to inactivity).
