### ISSUE TITLE
Broke my installed package and Can't reinstall pkg as there isn't any space.

### ISSUE THREAD

**Issue by chumunga** [gozoinks/unifi-pfsense#216]
I am currently working out an issue on Netgate forums, where my previously installed packages (snort and squid that im certain of) are gone, and when i tried to reinstall I get disk space issue and even after checking my my partitions all looks as it should and it is suggested to me that since unifi controller was the last thing i install it may have broken my repo and an admin suggested,
"...now it's trying to uninstall pfSense because that doesn't exist there". I would like to to see if anyone knows or have an idea? See link below. 

At the moment I was able to install Suricata which is nice, not sure why i was able to install this but not some other packages namely Snort or Squid and a few other randoms i tried.

https://forum.netgate.com/topic/158632/snort-previously-installed-and-its-gone/6

**Comment by gnkidwell** [comment]
> I am currently working out an issue on Netgate forums, where my previously installed packages (snort and squid that im certain of) are gone, and when i tried to reinstall I get disk space issue and even after checking my my partitions all looks as it should and it is suggested to me that since unifi controller was the last thing i install it may have broken my repo and an admin suggested,
> "...now it's trying to uninstall pfSense because that doesn't exist there". I would like to to see if anyone knows or have an idea? See link below.
> 
> At the moment I was able to install Suricata which is nice, not sure why i was able to install this but not some other packages namely Snort or Squid and a few other randoms i tried.
> 
> https://forum.netgate.com/topic/158632/snort-previously-installed-and-its-gone/6

Where did you get your install link from, if you grabbed it from one of my pull requests I do have a package lock enabled on all PFSense vital packages... How were you trying to install Snort and Squid, was that being done from terminal? What happens if you do it from the webpage?

**Comment by gnkidwell** [comment]
Actually come to think of it all, looking at your link nothing in my updated script would cause this either. I am not exactly sure what is causing that, but I can tell you it is not the Unifi install script. TActually come to think of it all, looking at your link nothing in my updated script would cause this either. I am not exactly sure what is causing that, but I can tell you it is not the Unifi install script. There is something definitely borked there though, what version of PFSense were you running? Snort should not be trying to delete PFSense, that part makes absolutely no sense...

**Comment by chumunga** [comment]
I am running the latest version 2.5.1 or whatever is on pfsense download
page. I did run the script twice by accident.

**Comment by gnkidwell** [comment]
Chumunga version 2.5 is Developmental, and I can confirm this script does not break 2.5 or 2.4.5 (which is the current stable release)... No matter how many times you run this script it will not cause PFSense to break in this manner...

**Comment by gnkidwell** [comment]
@chumunga, have you tried the latest version of the script? Are you running successfully now? If so lets close this out...?

**Comment by gnkidwell** [comment]
Stale issue closing this out.

**Comment by chumunga** [comment]
Yes, it has been working well! Sorry for the late reply.
