### ISSUE TITLE
Error after update: ...libjli.so: Undefined symbol "stat@FBSD_1.5"

### ISSUE THREAD

**Issue by Fry-kun** [gozoinks/unifi-pfsense#225]
Just tried to update to latest version, getting an error while starting up unifi.sh:
`/usr/local/openjdk8/bin/../lib/amd64/jli/libjli.so: Undefined symbol "stat@FBSD_1.5"`

Pfsense version is
```
2.4.5-RELEASE-p1 (amd64)
built on Tue Jun 02 17:51:17 EDT 2020
FreeBSD 11.3-STABLE
```

**Comment by Fry-kun** [comment]
Digging in further, looks like even `pkg` doesn't want to run on the system.
I think there's some weirdness with `pkg` when there's a freebsd version bump (e.g. right now) -- some dependencies may get auto-upgraded & system may become unusable :(

**Comment by gnkidwell** [comment]
> Digging in further, looks like even `pkg` doesn't want to run on the system.
> I think there's some weirdness with `pkg` when there's a freebsd version bump (e.g. right now) -- some dependencies may get auto-upgraded & system may become unusable :(

What version of BSD did you go to? Was not aware their was a BSD update for 2.4.5?

**Comment by Fry-kun** [comment]
pfsense just updated to 2.5.0
I saw the dashboard was saying "upgrade available", etc.

I chose to ignore this and just wanted to update unifi -- ran the script and ended up without working unifi or pkg

**Comment by Fry-kun** [comment]
Note: when this pfsense update is available, running `pkg` with any params prints this to stderr:
`pkg: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended`

**Comment by Fry-kun** [comment]
Ended up running `pfSense-upgrade` since web UI wasn't upgrading properly.
`pkg check -s -a` came up with a bunch of packages missing files. Most of those I was able to reinstall with `pkg install -f ...` but a few couldn't be. Turned out that those were installed by unifi script & locked. Unlocked and removed them manually, then ran unifi install script again, which installed them properly.

**Comment by gnkidwell** [comment]
@Fry-kun that makes sense I was going to bring that up, but have been a bit busy today. Glad you are working again.

**Comment by Fry-kun** [comment]
I hope you can add some quick-n-dirty detection for this in the script and ask the user if they want to continue...

**Comment by gnkidwell** [comment]
> I hope you can add some quick-n-dirty detection for this in the script and ask the user if they want to continue...

Fry-kun this is definitely not normal behavior the PFSense script, while it does lock some packages down, this sounds like a direct error that occurred during the upgrade. Thus causing more things to break, I think just documenting unlocking packages for now might resolve the issue for some.

**Comment by gnkidwell** [comment]
Closing this for now stale.
