### ISSUE TITLE
Slow guest portal

### ISSUE THREAD

**Issue by paulorochagodoi** [gozoinks/unifi-pfsense#226]
Hi, 

My pfsense takes long time to load the guest portal.
How can I speed it up? or wich configs should apply?

thanks

**Comment by tong2x** [comment]
unifi issue?

**Comment by paulorochagodoi** [comment]
yes, unifi guest portal

**Comment by tong2x** [comment]
disabling unifi, speed ups your pfsense portal?

maybe you could provide more details, your hard spec pf sense versions and unifi version

**Comment by paulorochagodoi** [comment]
It's everything fine with pfsense portal and everything else.
I'm just having slow speed times with unifi guest portal, it takes 10 minutes to load.
T340 with raid 1, 500gb SSDs, 8gb ram, 8 core CPU

**Comment by gnkidwell** [comment]
> It's everything fine with pfsense portal and everything else.
> I'm just having slow speed times with unifi guest portal, it takes 10 minutes to load.
> T340 with raid 1, 500gb SSDs, 8gb ram, 8 core CPU

Any more information that you can provide? Are you running vlans per chance?

**Comment by gnkidwell** [comment]
Stale issue closing this for now.
