### ISSUE TITLE
2.5.0

### ISSUE THREAD

**Issue by marcelloNF** [gozoinks/unifi-pfsense#227]
I just updated pfSense.
I reinstalled unifi-pfsense but I got this while launching 
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/OSInfo
	at com.ubnt.service.system.S.<clinit>(Unknown Source)
	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.OSInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more

**Comment by gnkidwell** [comment]
@marcelloNF do this for now, sometimes major os changes like jumping from one version of BSD to another can cause this to occur... Due to the package lock I need you to unlock some packages... In the shell type the following commands and then rerun the script...
pkg unlock -yq javavmwrapper
pkg unlock -yq java-zoneinfo
pkg unlock -yq openjdk8
pkg unlock -yq snappyjava
pkg unlock -yq snappy
pkg unlock -yq mongodb36

pkg remove -y javavmwrapper
pkg remove -y java-zoneinfo
pkg remove -y openjdk8
pkg remove -y  snappyjava
pkg remove -y snappy

**Comment by marcelloNF** [comment]
Hi thanks for your support, I now get this message:
[2.5.0-RELEASE][admin@NF*.n*l.com]/root: service unifi.sh start
Starting UniFi controller. 
eval: /usr/local/bin/java: not found

Should I reinstall java? witch one?

Thanks
Best
M

**Comment by dvdp** [comment]
Yep - just happened to me too ...
What I did is download the installation script and just remove the unzip/install part of Unifi.zip
then ran the script - installed all packages nicely - including java - and started the controller
Piece of cake

**Comment by marcelloNF** [comment]
So what should I do?

[2.5.0-RELEASE][admin@N*.n*.com]/root: fetch -o - https://git.io/j7Jy | sh -s
-                                                     7562  B 6999 kBps    00s
Stopping the unifi service...Signaling the UniFi controller to stop...eval: /usr/local/bin/java: not found
 acknowledged.
Waiting for the UniFi controller to stop (this can take a long time)...pgrep: Cannot get process list (kvm_getprocs: No such process)
 stopped.
 done.
sh: mongod: not found
Mounting new filesystems... done.
Removing packages discontinued...
 done.
Installing required packages...
packagesite.txz                                       5919 kB 6557 kBps    01s
x packagesite.yaml.sig
x packagesite.yaml.pub
x packagesite.yaml
Package png-1.6.37_1 already installed.
Package freetype2-2.10.4 already installed.
Package fontconfig-2.13.93,1 already installed.
Package alsa-lib-1.1.2_2 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2020.1 already installed.
Package libXdmcp-1.1.3 already installed.
Package libpthread-stubs-0.4 already installed.
Package libXau-1.0.9 already installed.
Package libxcb-1.14_1 already installed.
Package libICE-1.0.10,1 already installed.
Package libSM-1.2.3,1 already installed.
Package libX11-1.6.12,1 already installed.
Package libXfixes-5.0.3_2 already installed.
Package libXext-1.3.4,1 already installed.
Package libXi-1.7.10,1 already installed.
Package libXt-1.2.1,1 already installed.
Package libXtst-1.2.3_2 already installed.
Package libXrender-0.9.10_2 already installed.
Package libinotify-20180201_2 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
No packages matched for pattern 'snappyjava'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package cyrus-sasl-2.1.27_1 already installed.
Package icu-68.2,1 already installed.
Package boost-libs-1.72.0_3 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package unzip-6.0_8 already installed.
Package pcre-8.44 already installed.
 done.
UniFi.unix.zip                                         140 MB 8675 kBps    16s
 done.
Installing UniFi controller in /usr/local...Archive:  UniFi.unix.zip

**Comment by dvdp** [comment]
No offense but I got a feeling you're not very familiar with Linux:
With that command, you launched the installer: the  | sh -s at the end of the command pipes the output of the fetch to a shell thus executing it. What you should have done instead is something like:
fetch -o unifi_install.sh  https://git.io/j7Jy
chmod u+x unifi_install.sh 
next edit unifi_install.sh and comment the lines that unpack the zip to /usr/local and then run it with ./unifi_install.sh
Too late for that now - if you did not manually install a newer Unifi version, you just overwrote your version with the one referenced by the installation script. The script backs up and restores the data directory so you should be good.
Are things working now?

**Comment by marcelloNF** [comment]
Don't worry, no I'm not so familiar to Linux.
I know I actually updated the controller but I have the configuration backup file on my computer.
What do you suggest to try to do?
Thanks a lot for the support

**Comment by dvdp** [comment]
Your previous post ended with:
...
Package unzip-6.0_8 already installed.
Package pcre-8.44 already installed.
done.
UniFi.unix.zip 140 MB 8675 kBps 16s
done.
Installing UniFi controller in /usr/local...Archive: UniFi.unix.zip

That was not the final output line I think - can you get post the rest ?
The last line should be about starting the service like "Starting the unifi service..."
What do you now get if you jut run 'service unifi.sh start' ?

**Comment by marcelloNF** [comment]
Hi, this is what I get by starting the service
[2.5.0-RELEASE][admin@*.*.com]/root: service unifi.sh start
Starting UniFi controller. 
eval: /usr/local/bin/java: not found

**Comment by dvdp** [comment]
OK - since you have a backup and the installation script does a backup and restore of your data, could you run the following commands (one at a time) and post the complete output of the last command
cd
fetch -o unifi_install.sh https://git.io/j7Jy
chmod u+x unifi_install.sh
./unifi_install.sh

= go to the login dir, download the script and put it a file called unifi_install.sh, make that file executable and run it

**Comment by marcelloNF** [comment]
I edited unifi_install.sh as you said before (commenting unifi installation).

this is the output, it seems not able to get the java packets because of a "SSL_library_init" issue?

[2.5.0-RELEASE][admin@..com]/root: ./unifi_install.sh
Stopping the unifi service...There is no pid file. The controller may not be running.
 done.
./unifi_install.sh: mongod: not found
Mounting new filesystems... done.
Removing packages discontinued...
 done.
Installing required packages...
packagesite.txz                                       5919 kB 6775 kBps    01s
x packagesite.yaml.sig
x packagesite.yaml.pub
x packagesite.yaml
Package png-1.6.37_1 already installed.
Package freetype2-2.10.4 already installed.
Package fontconfig-2.13.93,1 already installed.
Package alsa-lib-1.1.2_2 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package libfontenc-1.1.4 already installed.
Package mkfontscale-1.2.1 already installed.
Package dejavu-2.37_1 already installed.
Package giflib-5.2.1 already installed.
Package xorgproto-2020.1 already installed.
Package libXdmcp-1.1.3 already installed.
Package libpthread-stubs-0.4 already installed.
Package libXau-1.0.9 already installed.
Package libxcb-1.14_1 already installed.
Package libICE-1.0.10,1 already installed.
Package libSM-1.2.3,1 already installed.
Package libX11-1.6.12,1 already installed.
Package libXfixes-5.0.3_2 already installed.
Package libXext-1.3.4,1 already installed.
Package libXi-1.7.10,1 already installed.
Package libXt-1.2.1,1 already installed.
Package libXtst-1.2.3_2 already installed.
Package libXrender-0.9.10_2 already installed.
Package libinotify-20180201_2 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
No packages matched for pattern 'snappyjava'

Checking integrity... done (0 conflicting)
1 packages requested for removal: 0 locked, 1 missing
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package cyrus-sasl-2.1.27_1 already installed.
Package icu-68.2,1 already installed.
Package boost-libs-1.72.0_3 already installed.
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Package unzip-6.0_8 already installed.
Package pcre-8.44 already installed.
 done.
Checking partition size... done.
Updating snappy java...zipinfo:  cannot find or open UniFi.unix.zip, UniFi.unix.zip.zip or UniFi.unix.zip.ZIP.
ERROR: Could not locate UniFi's snappy java! AP adoption will most likely fail
/usr/local/etc/rc.d/unifi.sh                          1686  B 4067 kBps    00s
 done.

Thanks again

**Comment by dvdp** [comment]
Hmm - I searched/checked a bit more -not sure how come but the 3 lines
d-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "SSL_library_init"
Those are thrown when installing
AddPkg javavmwrapper
AddPkg java-zoneinfo
AddPkg openjdk8

That explains why java is missing - and why it complains about snappyjava
Can't tell where that error comes from - the script ran like a train on my box ...
Anyone else an idea?

**Comment by marcelloNF** [comment]
Hi thanks a lot for all your very fast support. I reinstalled from scratch pfSense and ubiquity controller and now all is fine.
God bless backups :-D

Thanks again

**Comment by gnkidwell** [comment]
User reinstalled PFSense.

**Comment by b4b857f6ee** [comment]
> Yep - just happened to me too ...
> What I did is download the installation script and just remove the unzip/install part of Unifi.zip
> then ran the script - installed all packages nicely - including java - and started the controller
> Piece of cake

You save me beautiful :D.

Thank you!
