### ISSUE TITLE
downgraded to 2.4.5_p1 pfsense 

### ISSUE THREAD

**Issue by Reddwarfusa** [gozoinks/unifi-pfsense#228]
Trying to install Unifi gateway after loading new PFSense box.  Had to reinstall 2.4.5_p1 because of PFATT at moment, but cannot get script for Unifi to run.

I receive this 
fetch -o - https://git.io/j7Jy | sh -s
-                                                     7562  B   80 MBps    00s
FreeBSD pkgng not installed. Installing...
pkg already bootstrapped at /usr/local/sbin/pkg
 done.
ERROR: pkgng installation failed. Exiting.

**Comment by Reddwarfusa** [comment]
Found the issue

pkg has not been updated
Ran pkg bootstrap -f

**Comment by gnkidwell** [comment]
Issue resolved, problem with PFSense installation.
