### ISSUE TITLE
Making mongod to be installed with proper dependency

### ISSUE THREAD

**Issue by kennylam777** [gozoinks/unifi-pfsense#23]
In some default installation, using "pkg install mongod" will still result a broken installation, the symptoms could be follows:
1. Executing: /usr/local/etc/rc.d/mongod onestart
   Result: /usr/local/etc/rc.d/mongod: WARNING: failed to start mongod
2. Executing: /usr/local/bin/mongod
   Result: Missing libpcrecpp.so.0 

When the above symptoms were shown , which imply that the pcre package may not be installead. However, execurint "pkg install pcre" may got a message of "pcre is up-to-date".

The workaround is to force all packages to be reinstalled, by executing follow command:
pkg upgrade -f

**Comment by gozoinks** [comment]
Why does pcre seem to be installed when it isn't?

I merged a change not long ago that explicitly installs pcre. If that doesn't do it, why not? 

It seems to me we should try to fix that rather than simply brute force a reinstallation of every package on the system.

**Comment by gnkidwell** [comment]
PFSense install script now has a Mongodb repair script added. Closing.
