### ISSUE TITLE
Ubiquiti has removed 4.7.6 zip package

### ISSUE THREAD

**Issue by Fogelholk** [gozoinks/unifi-pfsense#26]
Hi,

Just tried installing this and it seems that Ubiquiti has removed the 4.7.6-zip file from their download-server.

Latest version (at the moment) 4.8.14 seems to work after installing this package/fix:

http://scottn.us/2016/02/pfsense-unifi-controller-stuck-adopting/

Please update the installation script accordingly!

**Comment by gozoinks** [comment]
Thank you for the information; the script has been updated.
