### ISSUE TITLE
Unable to adopt UAP-LR after update

### ISSUE THREAD

**Issue by daniel-onisoru** [gozoinks/unifi-pfsense#27]
Hello,

I have updated the controller to the latest version 4.8.14, everything went fine.
Then I have updated the firmware on one of the AP and it seems it is unable to adopt it again.

In /var/log/messages on the AP in question I receive a server reject error:

`Mar 24 09:41:29 UBNT user.err syslog: ace_reporter.reporter_fail(): Server Reject (http://10.0.0.1:8080/inform)
Mar 24 09:41:29 UBNT user.err syslog: ace_reporter.reporter_fail(): initial contact failed #68, url=http://10.0.0.1:8080/inform, rc=5
`

The other APs on the older firmware work fine.
I've tried the usual, reseting the AP to default, doing a clean install of the controller, changing the inform url with set-inform, etc and nothing worked.
Also tried to install the controller on windows to see if it's an AP problem but it worked just fine.

Any ideas on this one ?
Thank you.

**Comment by daniel-onisoru** [comment]
It seems to be a java problem.
More specifically the snappy library doesn't work.

To fix it I've installed snappyjava and replaced /usr/local/UniFi/lib/snappy-java-1.0.5.jar with /usr/local/share/java/classes/snappy-java.jar

**Comment by 74kumi** [comment]
fetch http://pkg.freebsd.org/freebsd:10:x86:64/release_1/All/snappyjava-1.0.4.1_1.txz tar vfx snappyjava-1.0.4.1_1.txz cp ./usr/local/share/java/classes/snappy-java.jar /usr/local/UniFi/lib/snappy-java-1.0.5.jar

**Comment by jmcphail** [comment]
Latest install script update resolves this.  Please test and confirm.

**Comment by gnkidwell** [comment]
Stale issue closed due to newer script.
