### ISSUE TITLE
pfSense 2.2 (FreeBSD 10) rc.d changed

### ISSUE THREAD

**Issue by kohenkatz** [gozoinks/unifi-pfsense#3]
In FreeBSD 10 (which pfSense 2.2 is based on), there are two major changes that will be required.  This issue describes one of those changes. (The other is #2, which I will update).

As described [here](http://lists.freebsd.org/pipermail/freebsd-current/2012-January/031273.html), there is no longer a `set_rcvar` command, which is used in https://github.com/gozoinks/unifi-pfsense/blob/master/rc.d/unifi#L10.  The fix is to change this:

    rcvar=`set_rcvar`

to this:

    rcvar=unifi_enable

**Comment by bytestore** [comment]
From pfsense site https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages#Startup_Script_Notes

"Startup Script Notes

The usual rc.d scripts added to /usr/local/etc/rc.d/ will not function on a pfSense system. There is no rc.conf and one cannot be created as it will be deleted. A custom startup script must be created in /usr/local/etc/rc.d/ and its name must end with .sh and it must be marked executable (chmod +x), and it will run at boot time. Alternatively if it's something that can be started with a single command then it can easily be added as a <shellcmd> in config.xml."

**Comment by gozoinks** [comment]
Now that 2.2 is released, one magical weekend I intend to revisit all this. If anyone beats me to it, pull requests are welcome!

**Comment by gcohen55** [comment]
Beat ya! :)

I've put in a PR. I've set it up so that it'll only run on 2.2-RELEASE.

You should rename the unifi in rc.d to unifi.sh just to be consistent.

Let me know if you want me to make any more changes.

**Comment by gcohen55** [comment]
@gozoinks are you going to merge #6 ?

-g

**Comment by jackcarrozzo** [comment]
@gozoinks please merge this!

**Comment by gcohen55** [comment]
side note: pfsense 2.2.1 just came out, and officially this script won't support it. in the ideal world, this'll get merged, link gets fixed (for rc.d script), and then amend the script to include pfsense 2.2.1-RELEASE once we test and we're happy

**Comment by gozoinks** [comment]
It goes more quickly when I'm only merging what is needed to fix a problem.
Most of these changes are unrelated to the issue. Bear with me, or consider
forking.

On Tue, Mar 17, 2015 at 4:20 PM, gcohen55 <notifications@github.com> wrote:

> side note: pfsense 2.2.1 just came out, and officially this script won't
> support it. in the ideal world, this'll get merged, link gets fixed (for
> rc.d script), and then amend the script to include pfsense 2.2.1-RELEASE
> once we test and we're happy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gozoinks/unifi-pfsense/issues/3#issuecomment-82605304>
> .
>



-- 

j

**Comment by gcohen55** [comment]
@gozoinks -- no worries. the last thing I want to do is fork because it seems like this repo popular amongst the pfsense folks.

**Comment by gozoinks** [comment]
Thanks for understanding. I can tell the project is important to you, and I'm glad to see the broader level of interest in it.

Why don't you open some issues for the things you were fixing, like the version check and the error handling on the package installer. That'll make it easier to merge those in coherently. I'll make a couple branches of my own and add the variables and fix the rc.d scripts so those can be merged back, unless you want to do those as well?
