### ISSUE TITLE
Possible mongodb install fail & "How do you use this?"

### ISSUE THREAD

**Issue by TheSwede86** [gozoinks/unifi-pfsense#35]
Hi!

First of all - thanks! Really grateful for your work.
Tried this the first time now and I think (see below) that it installed OK and sorry for this very basic question:

1) How do you actually use it? I mean when I installed UniFi on my computer I had an icon in the systray where I launched the application and I saw on the "ToDo"-list that:
"pfSense user interface elements for managing the UniFi Controller." is something that is in the pipe but not implemented yet. If I try my AP:s IP with or without the port I can't connect to it (using my browser) although using the UniFi program on my computer launches the webgui for the AP.
2) It seems that I get an error regarding mongodb but unsure if it affects the package (since, well I haven't figured out how to actually use it yet). Please see attached output, row 22 & 23: http://pastebin.com/dUAjw53v

Thanks a lot once again and sorry for my stupid questions - TheSwede86

**Comment by jmcphail** [comment]
1)  After the installation script has run, you should be able to access the UniFi controller at https://<your host ip address>:8443

2)  Yes, I have seen the error message relating to the mongodb install.  I have not investigated it, but it does seem to run successfully despite it.

**Comment by TheSwede86** [comment]
Thank you very much for your reply.
Ah, of course its pfSense's own IP and then the portnumber (8443).
Although if I try it I get "The website could not be reached, it took too long to reply".
I can go into pfSenses webgui without any problem when I don't specify the port (8443) for UniFi.

If I check "Diagnostics / Sockets" in pfSense I can't see the port 8443 anywhere, shouldnt it be listed there since "Sockets" should show all ports pfSense itself is listning to?

I've even manually started the script with "service unifi.sh start" and I get "Starting UniFi Controller" after that command.

Sorry if I have missed something very basic here.

**Comment by gozoinks** [comment]
You'll certainly want 8443 permitted in firewall rules on the applicable interface.

You might also do a ps auxwww | grep java to see if ace.jar is running.

Finally, you can try starting ace.jar yourself to see what java might report.

**Comment by jmcphail** [comment]
That mongodb package install error mentioned above has now been addressed in #44

**Comment by gnkidwell** [comment]
Closing issue addressed in #44.
