### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Panja0** [gozoinks/unifi-pfsense#51]
I have installed it on my pfSense box and it was running great.
But I sold my Ubiquiti systems and now I want to uninstall the software.

How can I do that?

**Comment by Panja0** [comment]
Can someone please help me out?

Many thanks!

**Comment by kklouzal** [comment]
The package maintainer doesn't provide an uninstall script, best I can tell you to do is read through the install script and manually remove each package from shell in the opposite order it was installed..

That is until this gets turned into a REAL pfSense package..... (sooner the better!)

**Comment by Panja0** [comment]
Will do a fresh install of pfSense than and restore my settings.
Probably a bit quicker...

Thanks anyways.
