### ISSUE TITLE
snappyjava version embedded in pathname

### ISSUE THREAD

**Issue by gozoinks** [gozoinks/unifi-pfsense#66]
The unifi package includes a version of snappyjava that we have to replace with our own. The name of the bundled snappyjava file includes a version string, but the name of the file we need to swap in does not. We should automate detecting the name of the file we need to replace and renaming our file to match, so that upstream changes in that file don't break our script.

**Comment by jmcphail** [comment]
See #67 
Tested on 2.3.3-RELEASE with physical access point hardware.
