### ISSUE TITLE
AP stuck in 'Adopting' state

### ISSUE THREAD

**Issue by dvdp** [gozoinks/unifi-pfsense#69]
Hi,
Installed it on my pfSense box, and added my first AP. AP showed up in the console but when I approved it, it got stuck in the 'Adopting' state. Ssh to AP and then ran info, returned 'server reject'. After a long search I found this fix:
wget http://pkg.freebsd.org/freebsd:10:x86:64/release_1/All/snappyjava-1.0.4.1_1.txz
tar vfx snappyjava-1.0.4.1_1.txz
cp ./usr/local/share/java/classes/snappy-java.jar /usr/local/UniFi/lib/snappy-java-1.0.5.jar
From what I read this is a known problem and was supposed to be fixed in the latest releas(es) but apparantly it's not.
br
Danny

**Comment by gozoinks** [comment]
Is this related to our version string sniffing? We have to do a little dance to replace the version of snappyjava that comes with Unifi with the version that works on FreeBSD. The version names do not match, so we have to rename it (just as you've done). The script should do this automatically. Perhaps that is not working.

That "server reject" response is also consistent with an AP that can't take the latest firmware. I wonder if there is an interaction here. What model AP are you trying to adopt? Do you know the hardware revision or manufacture date? What firmware is on the AP when you try to adopt it, and if the controller pushes an update to the AP, can you tell what version the AP ends up with?

**Comment by dvdp** [comment]
Hi John, 

Imho it is not related to firmware. As I said upon startup, it reports to the controller 
and apparently, you can do a FW update without adopting. I tried that: it failed 
from the console (could also by snappy related - hard to tell). 
Then I ssh-ed to the AP and started an upgrade from there pointing to the right 
directory on the controller and that ran smoothly - alas still no adoption so I 
digged further until the snappyjava replacment solved my adoption issue. 

For the record: the fw that came along with the controller install was more 
recent than the one on the AP. After the upgrade, I noticed there was yet a newer 
release on the ubnt site so I downloaded that to the controller (making a new version dir) 
and ran another upgrade from the AP (ssh). 
I noticed that the controller reports the latest version that is listed on the ubnt 
site and it looks to me that an update will pull it straight from that site too. That 
will fail because it's an http request and there's a (non-transparant) proxy in 
between. 

Version info: 
- running Unifi controller 5.4.11 
- I was provisioning a UAP AC PRO (gen2) 
- fw now is 3.7.47.6194 

I'll see if I can get the mfg date and any other revision info over the weekend 
when I go on-site. 

Danny 



Van: "John Burwell" <notifications@github.com> 
Aan: "gozoinks/unifi-pfsense" <unifi-pfsense@noreply.github.com> 
Cc: "danny vandepol" <danny.vandepol@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Donderdag 16 maart 2017 16:19:37 
Onderwerp: Re: [gozoinks/unifi-pfsense] AP stuck in 'Adopting' state (#69) 



Is this related to our version string sniffing? We have to do a little dance to replace the version of snappyjava that comes with Unifi with the version that works on FreeBSD. The version names do not match, so we have to rename it (just as you've done). The script should do this automatically. Perhaps that is not working. 

That "server reject" response is also consistent with an AP that can't take the latest firmware. I wonder if there is an interaction here. What model AP are you trying to adopt? Do you know the hardware revision or manufacture date? What firmware is on the AP when you try to adopt it, and if the controller pushes an update to the AP, can you tell what version the AP ends up with?

**Comment by gozoinks** [comment]
If you know it's gen 2, then an AP that new shouldn't have the issue I was describing, as far as I know, so don't worry about getting the date and revision info.

**Comment by icem4n** [comment]
Hi, 

I'm had the exact same issue with server rejections.  To make things more exciting, I'm running this on pfSense 2.4beta.  I downloaded and modified the script to get FreeBSD v11 packages (I turned the "10"s in the URLs up to "11"), and it appears to work fine. But, as I mentioned I was getting the 'Server Reject' message when I ran INFO on the AP.

I tried Danny's fix, in my case it was:
fetch http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/snappyjava-1.0.4.1_2.txz
tar vfx snappyjava-1.0.4.1_2.txz
cp ./usr/local/share/java/classes/snappy-java.jar /usr/local/UniFi/lib/snappy-java-1.0.5.jar

That didn't do it, so I wanted to check and see what java versions were present:
ls -l /usr/local/UniFi/lib/snappy*
/usr/local/UniFi/lib/snappy-java-1.0.5.jar
/usr/local/UniFi/lib/snappy-java-1.0.5.jar.backup
/usr/local/UniFi/lib/snappy-java-1.1.2.6.jar

**Everything is working fine after:
fetch http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/snappyjava-1.0.4.1_2.txz
tar vfx snappyjava-1.0.4.1_2.txz
cp ./usr/local/share/java/classes/snappy-java.jar /usr/local/UniFi/lib/snappy-java-1.1.2.6.jar**

#####
Unifi Controller v5.5.19
pfSense v2.4.0.b.20170707.1504

**Comment by mac-linux-free** [comment]
works for me, too after fix from icem4n...thank you.

**Comment by dvdp** [comment]
I noticed that the recent versions of the unix package are using a different snappy-java version so just copy the one from the freebsd package dir to that version.
I hope this will keep on working for the next upcoming releases ...

**Comment by mac-linux-free** [comment]
works for me, too after fix from icem4n...thank you.

**Comment by gozoinks** [comment]
What do we want to do to fix this in the script?

**Comment by nitrocs** [comment]
the fix from icem4n worked for me as well
I had applied "fix" while running 5.4.11 and then ran the script to upgrade, but got stuck in adopting loop.
shut down service, re-did fix & started...all is good

seems as though the new version copy has to be done after the pf-unifi script does its install

**Comment by gozoinks** [comment]
If we have a fix, can I get a pull request?

**Comment by icem4n** [comment]
I would happily help, but I am not that familiar with GitHub or confident enough in my scripting.  Should we make two scripts?  One for pfSense v2.3 (FreeBSD v10) and one for pfSense v2.4 (FreeBSD v11)?
