### ISSUE TITLE
Unifi Updated to 5.4.14

### ISSUE THREAD

**Issue by gozoinks** [gozoinks/unifi-pfsense#70]
Any blockers on updating to 5.4.14?

**Comment by dvdp** [comment]
I'm running 5.5.9 ....

John Burwell <notifications@github.com> schreef op 6 april 2017 23:55:42 CEST:
>Any blockers on updating to 5.4.14?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gozoinks/unifi-pfsense/issues/70

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shaneallgeier** [comment]
If it's good enough for Ubiquiti's stable branch, then it's good enough for me.
