### ISSUE TITLE
Oracle Java Branch

### ISSUE THREAD

**Issue by mac-linux-free** [gozoinks/unifi-pfsense#74]
Hello,

cloud you please add an Oracle Java Branch? Though I have issues with the guest portal.
I installed unifi on an Arch VM with Oracel Java instead and the guest portal works there.

thx

**Comment by johnkeates** [comment]
What kind of issues do you have? I'm using whatever the script installs and it works here...

**Comment by gozoinks** [comment]
Ubiquiti has recently added some accommodations for Oracle Java, so I too am wondering what, if any, differences there really are. 

Philosophically, I'd prefer to continue using openjdk unless there is a specific constraint.

**Comment by mac-linux-free** [comment]
hi thx for your reply...the installer and nearly all functions working fine execpt the guest login portal redirection..if you define an open guest wifi with openjdk some iphones and android devices do not authenticate and do not redirect to the promotional url...if I change to oracle java everything is fine...sadly.

**Comment by johnkeates** [comment]
Strange, the Java part doesn't really have much to do with that. Seems like a storage issue rather than a JRE issue.

**Comment by gozoinks** [comment]
@mac-linux-free what is the procedure to reproduce the issue?

**Comment by mac-linux-free** [comment]
but on the same host? Iḿ fine now having a seperate vm for the unifi controller

**Comment by mac-linux-free** [comment]
this is a big hotel, a customer of mine...could try it on the next maintenance session

**Comment by gozoinks** [comment]
I test issues on a clean, up-to-date installation of pfSense running in a vmware vm. I go through the guided setup from the command line using the defaults, enable ssh from the admin menu, and then log in via ssh, go to the shell, and run the unifi-pfsense script. If you can reproduce the problem in that environment, we can investigate further. Thanks for raising the issue.

**Comment by zjr8** [comment]
Sorry to threadjack - I have a portal setup running with the social auth running native on the PFsense host and haven't had any redirect issues unless I enable SSL redirection....( and I think that issue was my fault but haven't had a change to look more into it... ) Running 2.3.4-RELEASE / latest unifi controller version. Happy to share any network diagrams or configs to help debug your issues. @gozoinks  thanks for the install package saved tonnes of time

**Comment by mac-linux-free** [comment]
so i tried again with the actual package and the guest portal is only working for 1 hour after that nobody could login...turned of guest portal now my hotel guests are happy again...switching to linux and oracle jre asap
