### ISSUE TITLE
Package installation behavior

### ISSUE THREAD

**Issue by gcohen55** [gozoinks/unifi-pfsense#8]
pfSense 2.2 & 2.2.1 don't come with pkg-ng installed.

In order to make installation process easier, we should install pkg-ng for the user if it's not already installed, and then install the packages that UniFi depends on (mongodb, java, etc)...while also verifying that the packages were installed.

if pkg not installed
  attempt install it.
  verify its installed

for each required package
  attempt to install
  verify it's installed

**Comment by gozoinks** [comment]
What are the reasons for using something other than what comes with pfSense?

**Comment by armss001** [comment]
pkg-ng is needed for a the script to work from a fresh install of pfsense. I agree that is should be added to check/install from the script. I struggled with as it won't install any of the pkg's without it. Small thing but really easy to miss.

**Comment by gcohen55** [comment]
^^^ above. You can't actually install any packages without installing pkg-ng installed.

**Comment by gozoinks** [comment]
All right, fixed in master.

Relevant docs here: https://www.freebsd.org/doc/handbook/pkgng-intro.html

Thank you!
