### ISSUE TITLE
unable to pass install wizard on pfsense 2.4.1

### ISSUE THREAD

**Issue by ssbarnea** [gozoinks/unifi-pfsense#90]
I successfully run the installer on a new pfsense-2.4.1 and the service started but when I try to pass the Unify Setup Wizard, I get a wheel moving for some time and in the end I get the same page. I tried import settings or without, without any difference.

PS. Thanks for creating this project, I really appreciate your work and I will do my best to help with it as I find very useful to run UniFi Controller on the router.

**Comment by ssbarnea** [comment]
I was unable to find any logs regarding that problem but restarting the service did the trick and after this I was able to login. Well,... I had to reset the password inside the database because for some weird reason I was not able to login to the restored database using the old password.

Still, I think that there is a problem with restoration using the wizard so the bug should be kept open for some time.

**Comment by gnkidwell** [comment]
Stale issue no issues in latest script.
