### ISSUE TITLE
Describe what to do next once installed in the README

### ISSUE THREAD

**Issue by caliston** [gozoinks/unifi-pfsense#93]
I installed this (thanks, BTW!) but, having not used the controller before, I was then confused about what to do next.  I googled about, but got various conflicting information about how to connect to the Unifi controller.

It might make it easier for newbies to point out that:

- The default port is 8080 for HTTP and 8443 for HTTPS, ie once installed you go to http://your-server-ip:8080/ or https://your-server-ip:8443/ (and there will probably be a TLS certificate mismatch)
- A Unifi option will not appear in the pfSense menus (though it might be rather neat if it did that :-)

**Comment by EN4** [comment]
Next is the setup wizard. Youll need your pfsense ip address + controller port and put that in a broweser like firefox/chrome.

[ 192.168.1.1:8443 ]

**Comment by gozoinks** [comment]
@rsp2k PR?

**Comment by flowchartsman** [comment]
I got this.
