### ISSUE TITLE
1x1 pixel page loading after install

### ISSUE THREAD

**Issue by SMIncBrett** [gozoinks/unifi-pfsense#94]
I have a fairly new install on a pfSense 2.4 box where everything worked fine for about 3 weeks and then it started loading a blank page with "1x1 pixel GIF" in the browser title instead of the Unifi Controller when I go the address/port I was using to sign in.  It does look like it's displaying a single pixel that's a slightly different color in the middle.

I've tried re-running the installer and manually deleting the /usr/local/UniFi folder (as well as the automatically generated backups) to no avail!  Any ideas?  My hunch is a Java problem but this script looks like it would take care of that.

**Comment by bctrainers** [comment]
1x1 pixel gif sounds like the pfBlockerNG service running on port 8443. If you've installed pfBlockerNG, you'll either need to edit UniFi's listening port or pfBlockerNG's listening port for the DNSBL to not be 8443.

**Comment by SMIncBrett** [comment]
This was right on the money, fixed the issue immediately.  Changed the DNSBL to a different port.  Thank you!
