### ISSUE TITLE
Uninstall / Delete Unifi 

### ISSUE THREAD

**Issue by wampeee** [gozoinks/unifi-pfsense#95]
Greetings,

just a quick question - how can I remove Unifi and all its data from my pfSense? I was not able to do that with "pgk delete". Somebody got any idea?

Thanks a lot in advance!

Greetings
Wampeee

**Comment by jgcbaiz** [comment]
Hi! I am also looking to uninstall! Any clues?

**Comment by gozoinks** [comment]
I would just remove the files that were created by the script:
rm /usr/local/etc/rc.d/unifi.sh
rm -r /usr/localUniFi
